/*.$file${AOs::../src::alarm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: ClockAlarm.qm
* File:  ${AOs::../src::alarm.h}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${AOs::../src::alarm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef ALARM_H
#define ALARM_H

/*.$declare${AOs::Alarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Alarm} ...........................................................*/
typedef struct Alarm {
/* protected: */
    QHsm super;

/* private: */
    uint32_t alarm_time;
    uint8_t alarm_status;
} Alarm;

/* public: */
void Alarm_init(Alarm * const me);
void Alarm_dispatch(Alarm * const me);
void Alarm_set_alarm_time(Alarm * const me, uint32_t alarm_time);
void Alarm_set_status(Alarm * const me, uint8_t status);
uint32_t Alarm_get_alarm_time(Alarm * const me);

/* protected: */
QState Alarm_initial(Alarm * const me);
QState Alarm_ALARM(Alarm * const me);
/*.$enddecl${AOs::Alarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${AOs::Alarm_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Alarm_ctor} ......................................................*/
void Alarm_ctor(Alarm *const me);
/*.$enddecl${AOs::Alarm_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif